/**
 * Self-contained HTML report generator.
 *
 * Produces a standalone HTML file with inlined CSS. No JavaScript, no external
 * dependencies. Opens in any browser. Dark mode via prefers-color-scheme.
 *
 * Content: health score donut, root cause, finding count by severity,
 * all findings with descriptions and recommendations, timing summary.
 */
import type { AnalysisResult, HealthScore, Finding } from './types.js'

export interface HtmlReportOptions {
  title?: string
}

export function generateHtmlReport(
  result: AnalysisResult,
  healthScore: HealthScore,
  options?: HtmlReportOptions,
): string {
  const title = options?.title ?? 'HAR Analysis Report'
  const timestamp = new Date().toISOString()

  const { findings, rootCause, metadata, entries } = result
  const score = healthScore.score

  // Sort findings: critical first, then warning, then info
  const sorted = [...findings].sort((a, b) => {
    const order = { critical: 0, warning: 1, info: 2 }
    return order[a.severity] - order[b.severity]
  })

  const counts = {
    critical: findings.filter(f => f.severity === 'critical').length,
    warning: findings.filter(f => f.severity === 'warning').length,
    info: findings.filter(f => f.severity === 'info').length,
  }

  // Root cause
  const rcEntries = Object.entries(rootCause) as Array<[string, number]>
  rcEntries.sort((a, b) => b[1] - a[1])
  const topCause = rcEntries[0]
  const rootCauseText = topCause[1] === 0
    ? 'None (no findings)'
    : `${topCause[0].charAt(0).toUpperCase() + topCause[0].slice(1)} (${Math.round(topCause[1] * 100)}%)`

  // Timing
  const totalTimeMs = metadata.totalTimeMs
  const totalTimeStr = totalTimeMs >= 10_000
    ? `${(totalTimeMs / 1000).toFixed(1)}s`
    : `${Math.round(totalTimeMs)}ms`

  // Health score donut SVG
  const circumference = 2 * Math.PI * 45
  const offset = circumference * (1 - score / 100)
  const scoreColor = score >= 90 ? 'var(--good)' : score >= 50 ? 'var(--ok)' : 'var(--bad)'

  const donutSvg = `<svg viewBox="0 0 100 100" class="donut">
      <circle cx="50" cy="50" r="45" fill="none" stroke="var(--surface-hover)" stroke-width="8"/>
      <circle cx="50" cy="50" r="45" fill="none" stroke="${scoreColor}" stroke-width="8"
        stroke-dasharray="${circumference.toFixed(1)}" stroke-dashoffset="${offset.toFixed(1)}"
        stroke-linecap="round" transform="rotate(-90 50 50)"/>
      <text x="50" y="50" text-anchor="middle" dominant-baseline="central"
        fill="var(--text)" font-size="24" font-weight="700">${score}</text>
      <text x="50" y="66" text-anchor="middle" fill="var(--text-3)" font-size="8">/100</text>
    </svg>`

  // Findings HTML
  const findingsHtml = sorted.length > 0
    ? sorted.map(f => renderFinding(f)).join('\n')
    : '<p class="no-findings">No issues found.</p>'

  // Severity summary badges
  const badgesHtml = [
    counts.critical > 0 ? `<span class="badge critical">${counts.critical} critical</span>` : '',
    counts.warning > 0 ? `<span class="badge warning">${counts.warning} warning</span>` : '',
    counts.info > 0 ? `<span class="badge info">${counts.info} info</span>` : '',
  ].filter(Boolean).join('\n          ')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>${CSS}</style>
</head>
<body>
  <div class="report">
    <header class="report-header">
      <h1>${escapeHtml(title)}</h1>
      <time datetime="${timestamp}">${new Date(timestamp).toLocaleString()}</time>
    </header>

    <section class="summary">
      <div class="score-card">
        ${donutSvg}
      </div>
      <div class="stats">
        <div class="stat">
          <span class="stat-label">Requests</span>
          <span class="stat-value">${metadata.totalRequests}</span>
        </div>
        <div class="stat">
          <span class="stat-label">Total Time</span>
          <span class="stat-value">${totalTimeStr}</span>
        </div>
        <div class="stat">
          <span class="stat-label">Root Cause</span>
          <span class="stat-value">${rootCauseText}</span>
        </div>
        <div class="stat">
          <span class="stat-label">Analysis</span>
          <span class="stat-value">${metadata.analysisTimeMs}ms</span>
        </div>
      </div>
    </section>

    <section class="findings-section">
      <h2>Findings (${findings.length})</h2>
      <div class="badges">
        ${badgesHtml || '<span class="badge info">0 issues</span>'}
      </div>
      <div class="findings">
        ${findingsHtml}
      </div>
    </section>

    <footer class="report-footer">
      Generated by <a href="https://github.com/vegaPDX/har-o-scope">har-o-scope</a>
    </footer>
  </div>
</body>
</html>`
}

function renderFinding(f: Finding): string {
  return `<div class="finding ${f.severity}">
          <div class="finding-header">
            <span class="severity-badge ${f.severity}">${f.severity.toUpperCase()}</span>
            <span class="finding-title">${escapeHtml(f.title)}</span>
          </div>
          <p class="finding-desc">${escapeHtml(f.description)}</p>
          <p class="finding-fix">${escapeHtml(f.recommendation)}</p>
          <span class="finding-meta">Rule: ${escapeHtml(f.ruleId)} · Category: ${escapeHtml(f.category)} · Affected: ${f.affectedEntries.length} entries</span>
        </div>`
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

// ── Inlined CSS ─────────────────────────────────────────────────

const CSS = `
    :root {
      --bg: #0f1117;
      --surface: #1a1d27;
      --surface-hover: #252830;
      --border: #2f323b;
      --text: #e4e4e7;
      --text-2: #a1a1aa;
      --text-3: #71717a;
      --accent: #3b82f6;
      --critical: #ef4444;
      --critical-bg: #451a1a;
      --warning: #f59e0b;
      --warning-bg: #451a00;
      --info: #3b82f6;
      --info-bg: #1a2744;
      --good: #22c55e;
      --ok: #f59e0b;
      --bad: #ef4444;
    }
    @media (prefers-color-scheme: light) {
      :root {
        --bg: #ffffff;
        --surface: #f9fafb;
        --surface-hover: #f3f4f6;
        --border: #e5e7eb;
        --text: #18181b;
        --text-2: #52525b;
        --text-3: #a1a1aa;
        --critical-bg: #fef2f2;
        --warning-bg: #fffbeb;
        --info-bg: #eff6ff;
      }
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'IBM Plex Sans', system-ui, -apple-system, sans-serif;
      font-size: 14px;
      line-height: 1.5;
      color: var(--text);
      background: var(--bg);
    }
    .report {
      max-width: 720px;
      margin: 0 auto;
      padding: 32px 24px;
    }
    .report-header {
      margin-bottom: 32px;
    }
    .report-header h1 {
      font-size: 20px;
      font-weight: 700;
      margin-bottom: 4px;
    }
    .report-header time {
      font-size: 12px;
      color: var(--text-3);
    }
    .summary {
      display: flex;
      align-items: center;
      gap: 32px;
      padding: 24px;
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 8px;
      margin-bottom: 32px;
    }
    .score-card { flex-shrink: 0; }
    .donut { width: 100px; height: 100px; }
    .stats {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 16px;
      flex: 1;
    }
    .stat-label {
      display: block;
      font-size: 11px;
      font-weight: 500;
      color: var(--text-3);
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-bottom: 2px;
    }
    .stat-value {
      font-size: 16px;
      font-weight: 600;
      font-family: 'IBM Plex Mono', ui-monospace, monospace;
    }
    .findings-section { margin-bottom: 32px; }
    .findings-section h2 {
      font-size: 16px;
      font-weight: 600;
      margin-bottom: 8px;
    }
    .badges { display: flex; gap: 8px; margin-bottom: 16px; }
    .badge {
      font-size: 11px;
      font-weight: 600;
      padding: 2px 8px;
      border-radius: 4px;
    }
    .badge.critical { color: var(--critical); background: var(--critical-bg); }
    .badge.warning { color: var(--warning); background: var(--warning-bg); }
    .badge.info { color: var(--info); background: var(--info-bg); }
    .finding {
      padding: 16px;
      border: 1px solid var(--border);
      border-radius: 8px;
      margin-bottom: 12px;
    }
    .finding.critical { border-left: 3px solid var(--critical); }
    .finding.warning { border-left: 3px solid var(--warning); }
    .finding.info { border-left: 3px solid var(--info); }
    .finding-header {
      display: flex;
      align-items: center;
      gap: 8px;
      margin-bottom: 8px;
    }
    .severity-badge {
      font-size: 10px;
      font-weight: 700;
      padding: 1px 6px;
      border-radius: 3px;
      letter-spacing: 0.03em;
    }
    .severity-badge.critical { color: var(--critical); background: var(--critical-bg); }
    .severity-badge.warning { color: var(--warning); background: var(--warning-bg); }
    .severity-badge.info { color: var(--info); background: var(--info-bg); }
    .finding-title {
      font-size: 14px;
      font-weight: 600;
    }
    .finding-desc {
      font-size: 13px;
      color: var(--text-2);
      margin-bottom: 8px;
    }
    .finding-fix {
      font-size: 13px;
      color: var(--text-2);
      margin-bottom: 8px;
      padding-left: 12px;
      border-left: 2px solid var(--accent);
    }
    .finding-meta {
      font-size: 11px;
      color: var(--text-3);
      font-family: 'IBM Plex Mono', ui-monospace, monospace;
    }
    .no-findings {
      color: var(--text-2);
      padding: 24px;
      text-align: center;
    }
    .report-footer {
      text-align: center;
      font-size: 11px;
      color: var(--text-3);
      padding-top: 24px;
      border-top: 1px solid var(--border);
    }
    .report-footer a {
      color: var(--accent);
      text-decoration: none;
    }
    @media (max-width: 500px) {
      .summary { flex-direction: column; gap: 16px; }
      .stats { grid-template-columns: 1fr 1fr; }
    }
`
