import { useCallback, useState } from 'react'
import type { AnalysisResult, HealthScore } from '../lib/types'
import { generateHtmlReport } from '../lib/html-report'
import { useToast } from './Toast'

interface ExportButtonsProps {
  result: AnalysisResult
  healthScore: HealthScore
  fileName: string
}

type ExportFormat = 'json' | 'csv' | 'markdown' | 'html'

function generateJson(result: AnalysisResult, healthScore: HealthScore): string {
  return JSON.stringify({
    healthScore: healthScore.score,
    breakdown: healthScore.breakdown,
    findings: result.findings.map((f) => ({
      ruleId: f.ruleId,
      severity: f.severity,
      category: f.category,
      title: f.title,
      description: f.description,
      recommendation: f.recommendation,
      affectedEntries: f.affectedEntries.length,
    })),
    rootCause: result.rootCause,
    metadata: result.metadata,
  }, null, 2)
}

function generateCsv(result: AnalysisResult): string {
  const headers = ['Rule ID', 'Severity', 'Category', 'Title', 'Affected Entries']
  const rows = result.findings.map((f) => [
    f.ruleId,
    f.severity,
    f.category,
    `"${f.title.replace(/"/g, '""')}"`,
    f.affectedEntries.length,
  ])
  return [headers.join(','), ...rows.map((r) => r.join(','))].join('\n')
}

function generateMarkdown(result: AnalysisResult, healthScore: HealthScore, fileName: string): string {
  const lines: string[] = [
    `# HAR Analysis Report`,
    ``,
    `**File:** ${fileName}`,
    `**Health Score:** ${healthScore.score}/100`,
    `**Requests:** ${result.metadata.totalRequests}`,
    `**Root Cause:** ${getRootCause(result)}`,
    ``,
  ]

  if (result.findings.length > 0) {
    lines.push(`## Findings (${result.findings.length})`, ``)
    for (const f of result.findings) {
      lines.push(`### [${f.severity.toUpperCase()}] ${f.title}`)
      lines.push(``)
      lines.push(f.description)
      if (f.recommendation) {
        lines.push(``)
        lines.push(`**Fix:** ${f.recommendation}`)
      }
      lines.push(``)
      lines.push(`_Rule: ${f.ruleId} | Category: ${f.category} | Affected: ${f.affectedEntries.length} requests_`)
      lines.push(``)
    }
  } else {
    lines.push(`No issues found.`, ``)
  }

  lines.push(`---`, `Generated by har-o-scope`)
  return lines.join('\n')
}

function getRootCause(result: AnalysisResult): string {
  const { rootCause } = result
  const max = Math.max(rootCause.client, rootCause.network, rootCause.server)
  if (max === 0) return 'None'
  if (rootCause.server === max) return `Server (${Math.round(max * 100)}%)`
  if (rootCause.network === max) return `Network (${Math.round(max * 100)}%)`
  return `Client (${Math.round(max * 100)}%)`
}

function download(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function ExportButtons({ result, healthScore, fileName }: ExportButtonsProps) {
  const [open, setOpen] = useState(false)
  const { addToast } = useToast()

  const handleExport = useCallback((format: ExportFormat) => {
    const baseName = fileName.replace(/\.(har|json)$/i, '')
    switch (format) {
      case 'json':
        download(generateJson(result, healthScore), `${baseName}-report.json`, 'application/json')
        break
      case 'csv':
        download(generateCsv(result), `${baseName}-findings.csv`, 'text/csv')
        break
      case 'markdown':
        download(generateMarkdown(result, healthScore, fileName), `${baseName}-report.md`, 'text/markdown')
        break
      case 'html':
        download(generateHtmlReport(result, healthScore, { title: `${fileName} — Analysis Report` }), `${baseName}-report.html`, 'text/html')
        break
    }
    addToast(`Exported as ${format.toUpperCase()}`, 'success')
    setOpen(false)
  }, [result, healthScore, fileName, addToast])

  return (
    <div style={{ position: 'relative' }}>
      <button
        onClick={() => setOpen(!open)}
        aria-label="Export report"
        style={{
          background: 'var(--surface-2)',
          border: '1px solid var(--surface-3)',
          borderRadius: 'var(--radius-sm)',
          color: 'var(--text-secondary)',
          cursor: 'pointer',
          padding: '4px 8px',
          fontSize: 12,
          display: 'flex',
          alignItems: 'center',
          gap: 4,
        }}
      >
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3" />
        </svg>
        Export
      </button>
      {open && (
        <div
          style={{
            position: 'absolute',
            top: '100%',
            right: 0,
            marginTop: 4,
            background: 'var(--surface-2)',
            border: '1px solid var(--surface-3)',
            borderRadius: 'var(--radius-md)',
            padding: 4,
            zIndex: 100,
            minWidth: 140,
          }}
        >
          {(['json', 'csv', 'markdown', 'html'] as const).map((fmt) => (
            <button
              key={fmt}
              onClick={() => handleExport(fmt)}
              style={{
                display: 'block',
                width: '100%',
                background: 'transparent',
                border: 'none',
                color: 'var(--text-primary)',
                cursor: 'pointer',
                padding: '6px 8px',
                fontSize: 12,
                textAlign: 'left',
                borderRadius: 'var(--radius-sm)',
              }}
              onMouseEnter={(e) => { e.currentTarget.style.background = 'var(--surface-3)' }}
              onMouseLeave={(e) => { e.currentTarget.style.background = 'transparent' }}
            >
              {fmt.toUpperCase()}
            </button>
          ))}
        </div>
      )}
    </div>
  )
}
